FROM python:3.8.3
RUN pip install --no-cache-dir -r requirements.txt
 
# WORKDIR /usr/src/app

# COPY requirements_dev.txt ./
# RUN pip install --no-cache-dir -r requirements.txt

# COPY . .

# CMD [ "python", "./your-daemon-or-script.py" ]